#----------------------------------------------
# BECOME: yes
# VAULT: no
#----------------------------------------------
---
- name: Proxmox - banner disable
  hosts: '{{ HOSTS | default("localhost") }}'
  gather_facts: true
  gather_subset:
    - '!all'

  pre_tasks:
    - name: Assertions - OS
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == 'Debian'


  tasks:
    - name: Clear banner files
      become: true
      register: __result
      ansible.builtin.copy:
        content: ''
        dest: '{{ item }}'
        owner: root
        group: root
        mode: '0644'
      loop:
        - /etc/issue
        - /etc/issue.net
        - /etc/motd
        - /run/motd.dynamic


    - name: Set banner file as immutable if changed
      loop: '{{ __result.results }}'
      when: 'item.changed'
      ansible.builtin.command:
        cmd: 'chattr +i {{ item.dest }}'


    - name: Disable pam_motd.so in /etc/pam.d/sshd
      become: true
      ansible.builtin.replace:
        path: '/etc/pam.d/sshd'
        regexp: '^(session\s+optional\s+pam_motd[.]so\s+.*)$'
        replace: '# \1'
        backup: true

