#----------------------------------------------
# BECOME: yes
# VAULT: no
#----------------------------------------------
---
- name: (Local) Clear SSH Known Hosts File
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: clear ssh known hosts file
      ansible.builtin.copy:
        content: ''
        dest: /root/.ssh/known_hosts



- name: (Remote) Proxmox - SSH regenerate host keys
  hosts: '{{ HOSTS | default("localhost") }}'
  gather_facts: true
  gather_subset:
    - '!all'

  pre_tasks:
    - name: Assertions - OS
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == 'Debian'


  tasks:
    - name: Find ssh host key files in /etc/ssh/ssh_host_*
      register: __find_result
      ansible.builtin.find:
        paths: /etc/ssh/
        patterns: 'ssh_host_*'
        use_regex: false
        file_type: file


    - name: Fact
      ansible.builtin.set_fact:
        __ssh_host_key_filenames: '{{ __find_result.files | map(attribute="path") }}'


    - name: Print found ssh host key files
      ansible.builtin.debug:
        var: __ssh_host_key_filenames


    - name: Delete found ssh host key files
      become: true
      loop: '{{ __ssh_host_key_filenames }}'
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent


    - name: Regenerate SSH Host Key - RSA
      become: true
      ansible.builtin.shell:
        cmd: 'ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ""'


    - name: Regenerate SSH Host Key - ECDSA
      become: true
      ansible.builtin.shell:
        cmd: 'ssh-keygen -t ecdsa -b 384 -f /etc/ssh/ssh_host_ecdsa_key -N ""'


    - name: Restart SSH server
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted


- name: (Local) Clear SSH Known Hosts File
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: clear ssh known hosts content
      ansible.builtin.copy:
        content: ''
        dest: /root/.ssh/known_hosts



