#----------------------------------------------
# BECOME: yes
# VAULT: yes
#   - ANSIBLE_NEW_PASSWORD (str): change root user's password to this
#----------------------------------------------
---
- name: Proxmox - change root user password
  hosts: '{{ HOSTS | default(localhost) }}'
  gather_facts: true
  gather_subset:
    - '!all'

  pre_tasks:
    - name: Assertions - OS
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == 'Debian'


    - name: Assertions - Variables
      ansible.builtin.assert:
        that:
          - ANSIBLE_NEW_PASSWORD is defined and ANSIBLE_NEW_PASSWORD|length>0

  tasks:
    - name: Change password
      become: true
      no_log: true
      ansible.builtin.user:
        name: 'root'
        password: '{{ ANSIBLE_NEW_PASSWORD | ansible.builtin.password_hash("sha512") }}'
        update_password: 'always'

