#----------------------------------------------
# BECOME: yes
# VAULT: no
#----------------------------------------------
---
- name: Proxmox - disable Kernel Samepage Merging (KSM) service
  hosts: '{{ HOSTS | default(localhost) }}'
  gather_facts: true
  gather_subset:
    - '!all'

  pre_tasks:
    - name: Assertions - OS
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == 'Debian'

  tasks:
    - name: Disable ksmtuned.service
      become: true
      ansible.builtin.systemd_service:
        name: ksmtuned.service
        enabled: false
        masked: true


