#----------------------------------------------
# BECOME: no
# VAULT: yes
#   - PROXMOX_USER (str): (e.g. 'root')
#   - PROXMOX_TOKEN_ID (str): Create new API token in Proxmox Web UI > Datacenter > Permissions > API Tokens > Add
#   - PROXMOX_TOKEN_SECRET (str): Copy and paste from Proxmox Web UI
#   - PROXMOX_HOST (str): (e.g. '192.168.1.100')
#   - PROXMOX_PORT (str): (e.g. '8006')
#   - PROXMOX_VALIDATE_CERTS (bool): (e.g. true)
# COLLECTIONS:
#   - community.proxmox
# PIP:
#   - proxmoxer
#   - requests
#----------------------------------------------
---
- name: Proxmox - Node - Firewall - insert security group
  hosts: 'localhost'
  connection: local
  gather_facts: true
  gather_subset:
    - '!all'

  vars:
    PROXMOX_NODE: 'pve'
    PROXMOX_CLUSTER_FIREWALL_SECURITY_GROUP: 'ansible_managed'
    __PROXMOX_AUTH_SETTINGS__: &PROXMOX_AUTH_SETTINGS
        api_user: '{{ PROXMOX_USER }}'
        api_token_id: '{{ PROXMOX_TOKEN_ID }}'
        api_token_secret: '{{ PROXMOX_TOKEN_SECRET }}'
        api_host: '{{ PROXMOX_HOST }}'
        api_port: '{{ PROXMOX_PORT }}'
        validate_certs: '{{ PROXMOX_VALIDATE_CERTS }}'

  pre_tasks:
    - name: Assertions - Variables
      ansible.builtin.assert:
        that:
          - PROXMOX_USER is defined and PROXMOX_USER|length>0
          - PROXMOX_TOKEN_ID is defined and PROXMOX_TOKEN_ID|length>0
          - PROXMOX_TOKEN_SECRET is defined and PROXMOX_TOKEN_SECRET|length>0
          - PROXMOX_HOST is defined and PROXMOX_HOST|length>0
          - PROXMOX_PORT is defined and PROXMOX_PORT|length>0
          - 'PROXMOX_VALIDATE_CERTS is defined and PROXMOX_VALIDATE_CERTS|type_debug=="bool"'

  tasks:
    - name: Insert security group to node firewall
      community.proxmox.proxmox_firewall:
        <<: *PROXMOX_AUTH_SETTINGS
        level: 'node'
        node: '{{ PROXMOX_NODE }}'
        rules:
          - pos: 0
            comment: 'Insert "ansible_managed" security group'
            action: '{{ PROXMOX_CLUSTER_FIREWALL_SECURITY_GROUP }}'
            type: 'group'
            enable: true

