#----------------------------------------------
# BECOME: yes
# VAULT: no
#----------------------------------------------
---
- name: Proxmox - install sudo
  hosts: '{{ HOSTS | default("localhost") }}'
  gather_facts: true
  gather_subset:
    - '!all'

  pre_tasks:
    - name: Assertions - OS
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family == 'Debian'

  tasks:
    - name: Install sudo
      become: true
      ansible.builtin.apt:
        name: sudo
        state: present

