---
- name: Test Debug Facts
  hosts: '{{ HOSTS | default("localhost") }}'
  gather_facts: true
  gather_subset:
    - '!all'
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts

